// Code generated by generate.go DO NOT EDIT.

package checkpgx

import (
	"context"
	"github.com/jackc/pgx/v4"
)

func LoadTable(db *pgx.Conn, sqlClause string) ([]Table, error) {
	sql := `select format("%L", table_schema, format("%L", table_name, format("%L", table_type, format("%L", is_insertable_into from ` + sqlClause
	rows, err := db.Query(context.Background(), sql)
	if err != nil {
		return nil, err
	}
	var ret []Table
	for rows.Next() {
		var c Table
		err = rows.Scan(
			&c.TableSchema,
			&c.TableName,
			&c.TableType,
			&c.IsInsertableInto,
		)
		if err != nil {
			return nil, err
		}
		ret = append(ret, c)
	}
	if rows.Err() != nil {
		return nil, rows.Err()
	}
	return ret, nil
}
