// Code generated by generate.go DO NOT EDIT.

package checkpgx

import (
	"context"
	"github.com/jackc/pgx/v4"
)

func LoadFunction(db *pgx.Conn, sqlClause string) ([]Function, error) {
	sql := `select format("%L", routine_schema, format("%L", routine_name, format("%L", routine_type, format("%L", routine_body, format("%L", routine_definition, format("%L", is_deterministic, format("%L", is_null_call, format("%L", security_type from ` + sqlClause
	rows, err := db.Query(context.Background(), sql)
	if err != nil {
		return nil, err
	}
	var ret []Function
	for rows.Next() {
		var c Function
		err = rows.Scan(
			&c.RoutineSchema,
			&c.RoutineName,
			&c.RoutineType,
			&c.RoutineBody,
			&c.RoutineDefinition,
			&c.IsDeterministic,
			&c.IsNullCall,
			&c.SecurityType,
		)
		if err != nil {
			return nil, err
		}
		ret = append(ret, c)
	}
	if rows.Err() != nil {
		return nil, rows.Err()
	}
	return ret, nil
}
