// Code generated by schemadance DO NOT EDIT.
package {{.Package}}

import (
    "{{.MigratePath}}"
    "embed"
)
{{ range .Files }}
//go:embed{{.}}{{ end }}
var files embed.FS

var PatchSets = {{.MigratePackage}}.PatchSets {
    Files: files,
    Sets: []{{.MigratePackage}}.PatchSet{
{{ range .Sets}}         {{ title .}},
{{ end -}}
    },
}
